### ISSUE TITLE
Database Issues

### ISSUE THREAD

**Issue by b3coded** [overdevs/stockontrol#2]
Only Usuarios table could be created, new tables can not be created by the model

**Comment by saulojoab** [comment]
🤔

**Comment by saulojoab** [comment]
`System.Data.SqlClient.SqlException: 'Directory lookup for the file "F:\ASP.Net\Stockontroll\Stockontroll\App_Data\Stockontroll.mdf" failed with the operating system error 3(O sistema não pode encontrar o caminho especificado.).
CREATE DATABASE failed. Some file names listed could not be created. Check related errors.'`

The path for the database on my computer is different to yours. How should we handle that?
<b style="color:green">SOLUTION</b>: changed path on Web.config and added to gitignore

**Comment by saulojoab** [comment]
```
System.InvalidOperationException: 'Multiple object sets per type are not supported. The object sets 'Fornecedores' and 'Fornecedors' can both contain instances of type 'Stockontroll.Models.Fornecedor'.'
```

This one happens when we try to enter the Fornecedores page.
More info: <a href="https://pt.stackoverflow.com/questions/225237/erro-multiple-object-sets-per-type-are-not-supported">StackOverflow</a>

Found out: @b3coded was setting one context for each Model. That shouldn't happen, should be one context for all models.

<b style="color: green;">SOLUTION</b>: 
- Created a global Context
- Changed the reference on Web.config
- Deleted the Usuarios table
- Created a new migration then updated the database (needs to run the app so it'll work).
